version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8.5
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            python --version
            python setup.py install --user

workflows:
  main:
    jobs:
      - build
      - run:
          command: fastmlst -V
          name: Test

