{% set name = "fastmlst" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

channels:
- bioconda
- conda-forge
- defaults

build:
    noarch: python

source:
  # url: https://github.com/EnzoAndree/FastMLST/archive/v{{ version }}.tar.gz
  path: ./

requirements:
  build:
    - python {{ python }}

  run:
    - python
    - tqdm
    - pandas
    - blast>2.5
    - biopython
test:
  commands:
    - {{ name|lower }} -V
