{% set name = "FastMLST" %}
{% set version = "0.0.4" %}
{% set user = "EnzoAndree" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

channels:
- bioconda
- conda-forge
- defaults

build:
    noarch: python

source:
  url: https://github.com/{{ user }}/{{ name }}/archive/v{{ version }}.tar.gz
  # path: ./

requirements:
  build:
    - python {{ python }}

  run:
    - python>=3
    - tqdm
    - pandas
    - blast>=2.7
    - biopython
test:
  commands:
    - {{ name|lower }} -V

about:
  home: https://github.com/{{ user }}/{{ name }}
